export { Hero } from "./hero"
export { AboutSection } from "./about"
export { TrustedBySection } from "./trusted-by"
export { FeaturedProjects, FeaturedProjectsSkeleton } from "./featured-projects"
export { FeaturedBlogs } from "./featured-blogs"
export { LineBreaker } from "@/components/shared/line-breaker"
export { ManWhoCantBeMoved } from "./man-who-cant-be-moved"
export { FeaturedImageSection, FeaturedImageSkeleton } from "./featured-image"
export { default as StickyNotesLazy } from "./sticky-notes/sticky-notes-lazy"
